#后端端口号
server:
  port: 9090
#数据库数据源
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/agri-finance-trade?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: G200410115812
  jackson:
    time-zone: GMT+8
  #文件上传的配置
  servlet:
    multipart:
      enabled: true
      max-file-size: 500MB
      max-request-size: 500MB
  application:
    name: agri-finance-trade-server
  #静态资源放行
  mvc:
    static-path-pattern: /**
application:
  upload-path: ${user.home}\Desktop\AgriFinanceTradePlatform\agri-finance-trade-server\src\main\resources\static\file\upload
#mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true